/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 15-май-2021 19:30:01 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `long_link` CASCADE
;

DROP TABLE IF EXISTS `rules` CASCADE
;

DROP TABLE IF EXISTS `rules_definition` CASCADE
;

DROP TABLE IF EXISTS `short_link` CASCADE
;

DROP TABLE IF EXISTS `stats` CASCADE
;

DROP TABLE IF EXISTS `user` CASCADE
;

/* Create Tables */

CREATE TABLE `long_link`
(
	`ll_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`ll_sl_id` BIGINT UNSIGNED NOT NULL,
	`ll_long_url` VARCHAR(2084) NOT NULL,
	`ll_creation_time` DATETIME NOT NULL,
	CONSTRAINT `PK_long_link` PRIMARY KEY (`ll_id` ASC)
)

;

CREATE TABLE `rules`
(
	`r_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`r_rule_id` SMALLINT UNSIGNED NOT NULL,
	`r_short_url_id` BIGINT UNSIGNED NOT NULL,
	`r_param` VARCHAR(2048) NULL,
	`r_is_active` BOOL NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`r_id` ASC)
)

;

CREATE TABLE `rules_definition`
(
	`rd_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`rd_name` VARCHAR(128) NOT NULL,
	CONSTRAINT `PK_rules_definition` PRIMARY KEY (`rd_id` ASC)
)

;

CREATE TABLE `short_link`
(
	`sl_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`sl_user_id` INT UNSIGNED NOT NULL,
	`sl_short_url` VARCHAR(200) NOT NULL,
	`sl_creation_time` DATETIME NOT NULL,
	CONSTRAINT `PK_short_link` PRIMARY KEY (`sl_id` ASC)
)

;

CREATE TABLE `stats`
(
	`s_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`s_sl_id` BIGINT UNSIGNED NOT NULL,
	`s_date_time` DATETIME NOT NULL,
	`s_url_referrer` VARCHAR(2048) NULL,
	`s_platform` VARCHAR(255) NULL,
	`s_screen_width` MEDIUMINT UNSIGNED NULL,
	`s_screen_height` MEDIUMINT UNSIGNED NULL,
	`s_ip_address` VARCHAR(39) NULL,
	CONSTRAINT `PK_stats` PRIMARY KEY (`s_id` ASC)
)

;

CREATE TABLE `user`
(
	`u_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`u_login` VARCHAR(40) NOT NULL,
	`u_email` VARCHAR(256) NOT NULL,
	`u_hash` VARCHAR(60) NOT NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`u_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `long_link` 
 ADD INDEX `IXFK_long_link_short_link` (`ll_sl_id` ASC)
;

ALTER TABLE `rules` 
 ADD INDEX `IXFK_rules_rules_definition` (`r_rule_id` ASC)
;

ALTER TABLE `rules` 
 ADD INDEX `IXFK_rules_short_link` (`r_short_url_id` ASC)
;

ALTER TABLE `short_link` 
 ADD INDEX `IXFK_short_link_user` (`sl_user_id` ASC)
;

ALTER TABLE `stats` 
 ADD INDEX `IXFK_stats_short_link` (`s_sl_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `long_link` 
 ADD CONSTRAINT `FK_long_link_short_link`
	FOREIGN KEY (`ll_sl_id`) REFERENCES `short_link` (`sl_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `rules` 
 ADD CONSTRAINT `FK_rules_rules_definition`
	FOREIGN KEY (`r_rule_id`) REFERENCES `rules_definition` (`rd_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `rules` 
 ADD CONSTRAINT `FK_rules_short_link`
	FOREIGN KEY (`r_short_url_id`) REFERENCES `short_link` (`sl_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `short_link` 
 ADD CONSTRAINT `FK_short_link_user`
	FOREIGN KEY (`sl_user_id`) REFERENCES `user` (`u_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `stats` 
 ADD CONSTRAINT `FK_stats_short_link`
	FOREIGN KEY (`s_sl_id`) REFERENCES `short_link` (`sl_id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1
; 
